# permissions for end users to view schemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: schema-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: schema-viewer-role
rules:
- apiGroups:
  - client.sroperator.io
  resources:
  - schemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - client.sroperator.io
  resources:
  - schemas/status
  verbs:
  - get
