# permissions for end users to edit schemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: schema-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: schema-editor-role
rules:
- apiGroups:
  - client.sroperator.io
  resources:
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.sroperator.io
  resources:
  - schemas/status
  verbs:
  - get
