apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
  namespace: schema-registry-operator-system
spec:
  kafka:
    replicas: 1
    version: 3.7.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: saslplain
        port: 9094
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            org.apache.kafka.common.security.plain.PlainLoginModule: required
            plain.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin" user_admin="admin";
            sasl.enabled.mechanisms: PLAIN
        tls: false
        type: internal
    storage:
      type: persistent-claim
      size: 3Gi
    authorization:
      type: simple
      superUsers:
        - admin
    config:
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 3Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }
