apiVersion: client.sroperator.io/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: schema-sample
spec:
  # TODO(user): Add fields here
